# Generated by Django 4.2.7 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todotext', models.CharField(max_length=255)),
                ('tododesc', models.FloatField()),
            ],
        ),
    ]
